export default class InstructionMode{
  static BASIC_MODE = 'InstructionMode_BASIC';
  static THINKING_MODE = 'InstructionMode_THINKING';
  static AGENT_MODE = 'InstructionMode_AGENT';
  static NULL_MODE = 'InstructionMode_NULL'; // No Response will be generated by server.
}
